[tool.usort]
first_party_detection = false

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38, py39, py310, py311, py312, lint
skipsdist = True

[testenv]
passenv =
    http_proxy
    https_proxy
deps =
    -rrequirements.txt
allowlist_externals =
    bash
commands =
    bash scripts/run-python-tests.sh

[testenv:lint]
deps =
    black
    usort
    flake8
commands =
    black --check --diff client scripts tools
    usort check client scripts tools
    flake8 client scripts tools
"""
[tool.ufmt]
excludes = [
    "documentation/",
    "generate_taint_models/",
    "source/",
    "stubs/",
    "pyre2/",
]

[tool.pyre]
exclude = [
    ".*/documentation/.*",
    ".*/generate_taint_models/.*",
    ".*/scripts/.*",
    ".*/source/.*",
    ".*/pyre-check/stubs/.*",
]
ignore_all_errors = [
    "client/tests/configuration_test.py",
    "pyre_extensions/safe_json.py",
]
search_path = [
    { site-package = "click" },
    { site-package = "dataclasses_json" },
    { site-package = "flask" },
    { site-package = "flask_cors" },
    { site-package = "graphql" },
    { site-package = "libcst" },
    { site-package = "marshmallow" },
    { site-package = "psutil" },
    { site-package = "testslide" },
    { site-package = "toml" },
    { site-package = "tabulate" },
    { site-package = "tomli" },
    { is_toplevel_module = true, site-package = "typing_extensions" },
    { is_toplevel_module = true, site-package = "typing_inspect" },
]
source_directories = ["."]
strict = true
