# Simple workflow for deploying static content to GitHub Pages
name: Build and Test Pyrefly Website
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
    pull_request:
      types: [opened]
      paths:
        - 'website/**'

jobs:
  # Single deploy job since we're just deploying
  build_and_test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install yarn deps
        run: cd website && yarn install
      - name: Install wasm-pack
        run: cargo install wasm-pack wasm-opt
      - name: Use rust nightly
        run: rustup install nightly && rustup default nightly
      - name: Build
        working-directory: ./website
        run: cargo version && chmod +x scripts/build.sh && scripts/build.sh
      - name: Test
        working-directory: ./website
        run: yarn test
