name: pyre2
on:
  push:
  pull_request:
  schedule:
  - cron: '0 12 * * 1' # 12pm Monday
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: pyre2

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: windows-latest
            github_env: $env:GITHUB_ENV
    steps:
    - uses: actions/checkout@v4
    - name: set windows cargo home
      # we need to set CARGO_HOME to a high-up directory on Windows machines, since some dependencies cloned
      # by Cargo have long paths and will cause builds/tests to fail
      if: ${{ matrix.os == 'windows-latest' }}
      run: echo "CARGO_HOME=C:\\cargo" >> ${{ matrix.github_env }}
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-01-03
        components: clippy, rustfmt
    # We use rustfmt 2.0 for formatting, which differs from the released
    # version installed by Cargo
    # - run: cargo fmt -- --check
    - run: cargo clippy --release
    - run: cargo build --release
    - run: cargo test --release
