name: Build binaries

on:
  push:
    paths:
      - .github/workflows/build_pyre2_binaries.yml
  workflow_dispatch:

env:
  PACKAGE_NAME: pyrefly
  BINARY_NAME: pyrefly
  PYTHON_VERSION: "3.12"

jobs:
  macos:
    runs-on: macos-14
    strategy:
      matrix:
        platform:
          - target: x86_64
            arch: x64
          - target: aarch64
            arch: arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ matrix.platform.arch }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist
          working-directory: pyre2/pyre2
      - name: Test wheel
        if: ${{ startsWith(matrix.target, 'aarch64') }}
        run: |
          pip install pyre2/pyre2/dist/"${PACKAGE_NAME}"-*.whl --force-reinstall
          "${BINARY_NAME}" --help
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: pyre2/pyre2/dist

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - target: x86_64-pc-windows-msvc
            arch: x64
          - target: i686-pc-windows-msvc
            arch: x86
          - target: aarch64-pc-windows-msvc
            arch: x64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ matrix.platform.arch }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist
          working-directory: pyre2/pyre2
      - name: Test wheel
        if: ${{ !startsWith(matrix.platform.target, 'aarch64') }}
        shell: bash
        run: |
          python -m pip install pyre2/pyre2/dist/"${PACKAGE_NAME}"-*.whl --force-reinstall
          "${BINARY_NAME}" --help
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.target }}
          path: pyre2/pyre2/dist

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist
          working-directory: pyre2/pyre2
      - name: Test wheel
        if: ${{ startsWith(matrix.target, 'x86_64') }}
        run: |
          pip install pyre2/pyre2/dist/"${PACKAGE_NAME}"-*.whl --force-reinstall
          "${BINARY_NAME}" --help
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.target }}
          path: pyre2/pyre2/dist
